# Generated by Django 5.1 on 2024-09-10 19:08

import datetime
import django.db.models.deletion
import human_resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Last name')),
                ('pis_number', models.CharField(max_length=11, verbose_name='Pis number')),
            ],
            options={
                'verbose_name': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Employee Position',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='Day')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Holiday',
            },
        ),
        migrations.CreateModel(
            name='EmployeeHiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(blank=True, verbose_name='Admission date')),
                ('expiry_of_experience', models.DateField(blank=True, null=True, verbose_name='Expiry of experience')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Termination date')),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='human_resources.employee', verbose_name='Employee')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.enterprise', verbose_name='Enterprise')),
            ],
            options={
                'verbose_name': 'Employee Hiring',
                'verbose_name_plural': 'Employee Hirings',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('issue_date', models.DateField(verbose_name='Issue date')),
                ('expiration_date', models.DateField(verbose_name='Expiration date')),
                ('file', models.FileField(upload_to=human_resources.models.rename_file, verbose_name='File')),
                ('employee_hiring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='human_resources.employeehiring', verbose_name='Employee Hiring')),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.employeeposition', verbose_name='Position'),
        ),
        migrations.CreateModel(
            name='HoursBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('hours_owed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hours owed')),
                ('hours_compensated', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hours compensated')),
                ('employee_hiring', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.employeehiring', verbose_name='Employee Hiring')),
            ],
            options={
                'verbose_name': 'Hours Bank',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_entry', models.TimeField(blank=True, default=datetime.time(0, 0))),
                ('first_exit', models.TimeField(blank=True, default=datetime.time(0, 0))),
                ('second_entry', models.TimeField(blank=True, default=datetime.time(0, 0))),
                ('second_exit', models.TimeField(blank=True, default=datetime.time(0, 0))),
                ('third_entry', models.TimeField(blank=True, default=datetime.time(0, 0))),
                ('third_exit', models.TimeField(blank=True, default=datetime.time(0, 0))),
                ('employee_hiring', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.employeehiring')),
            ],
            options={
                'verbose_name': 'Point',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.point', verbose_name='Point')),
            ],
            options={
                'verbose_name': 'Observation',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=6, verbose_name='Level')),
                ('modality', models.CharField(choices=[('monthly', 'Monthly'), ('hourly', 'Hourly')], max_length=7, verbose_name='Modality')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Salary')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.employeeposition', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Salary',
            },
        ),
        migrations.AddField(
            model_name='employeehiring',
            name='salary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='human_resources.salary', verbose_name='Salary'),
        ),
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('previous_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Previous Salary')),
                ('adjustment_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=10, verbose_name='Adjustment Type')),
                ('adjustment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Adjustment Value')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.salary', verbose_name='Salary')),
            ],
            options={
                'verbose_name': 'Salary Adjustment',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('employee_hiring', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.employeehiring', verbose_name='Employee Hiring')),
            ],
            options={
                'verbose_name': 'Vacation',
            },
        ),
    ]
