# Generated by Django 5.1.1 on 2024-09-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='level',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Level'),
        ),
    ]
