# Generated by Django 5.1 on 2024-09-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_alter_salary_level'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('position', 'level'), name='unique_position_level'),
        ),
        migrations.AddConstraint(
            model_name='salaryadjustment',
            constraint=models.UniqueConstraint(fields=('date', 'salary'), name='unique_date_salary'),
        ),
    ]
