# Generated by Django 5.1 on 2024-09-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_alter_employeehiring_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pis_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Pis number'),
        ),
    ]
