# Generated by Django 5.1 on 2024-09-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0007_employeehiring_grant_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='paid_off',
            field=models.IntegerField(default=0),
        ),
    ]
