# Generated by Django 5.1 on 2024-09-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_vacation_paid_off'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vacation',
            constraint=models.UniqueConstraint(fields=('employee_hiring', 'start_date', 'end_date'), name='unique_employee_hiring_start_and_end_date'),
        ),
    ]
