# Generated by Django 5.1 on 2024-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_vacation_unique_employee_hiring_start_and_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
    ]
