# Generated by Django 5.1 on 2024-09-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_reason', models.CharField(max_length=80)),
                ('trade_name', models.CharField(max_length=80)),
                ('identification_number', models.CharField(max_length=14)),
            ],
        ),
    ]
