# Generated by Django 5.1 on 2024-09-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTypeForSped',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'item_types_for_sped',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'units_of_measure',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_type_for_sped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.itemtypeforsped')),
                ('categories', models.ManyToManyField(blank=True, to='product.productcategory')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.unitofmeasure')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
