# Generated by Django 5.1 on 2024-09-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_type', models.CharField(choices=[('AV', 'Avenida'), ('R', 'Rua'), ('T', 'Travessa'), ('FAZ', 'Fazenda')], default='R', max_length=3)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=50, null=True)),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warehouse_types',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disabled', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='warehouse.warehouseaddress')),
                ('w_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousetype')),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
    ]
