# Generated by Django 5.1 on 2024-09-24 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_enterprise_identification_number'),
        ('product', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.enterprise'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordered_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('stock_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.unitofmeasure')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='StorageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_position', models.CharField(max_length=20)),
                ('items', models.ManyToManyField(through='warehouse.Stock', to='product.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'storage_bins',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('movement_type', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('stock_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.unitofmeasure')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
                ('storage_bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.storagebin')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='storage_bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.storagebin'),
        ),
    ]
