# Generated by Django 5.1 on 2024-10-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('warehouse', '0003_alter_storagebin_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3, verbose_name='Movement type'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.serviceorder', verbose_name='Service Order'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='storage_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.storagebin', verbose_name='Storage Bin'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Warehouse'),
        ),
    ]
