# Generated by Django 5.1 on 2024-10-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_stockmovement_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='tax_invoice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tax Invoice'),
        ),
    ]
