# Generated by Django 5.1 on 2024-10-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_enterprise_identification_number'),
        ('product', '0003_alter_product_options_alter_productcategory_options_and_more'),
        ('warehouse', '0006_alter_stockmovement_tax_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-date'], 'verbose_name': 'Stock Movement'},
        ),
        migrations.AlterModelOptions(
            name='warehousetype',
            options={'verbose_name': 'Warehouse Type'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='storage_bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.storagebin', verbose_name='Storage Bin'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.unitofmeasure', verbose_name='UOM'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.enterprise', verbose_name='Enterprise'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='w_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousetype', verbose_name='Warehouse Type'),
        ),
        migrations.AlterField(
            model_name='warehouseaddress',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='warehouseaddress',
            name='complement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Complement'),
        ),
        migrations.AlterField(
            model_name='warehouseaddress',
            name='neighborhood',
            field=models.CharField(max_length=50, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='warehouseaddress',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='warehouseaddress',
            name='postal_code',
            field=models.CharField(max_length=9, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='warehouseaddress',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='warehouseaddress',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='warehouseaddress',
            name='street_type',
            field=models.CharField(choices=[('AV', 'Avenida'), ('R', 'Rua'), ('T', 'Travessa'), ('FAZ', 'Fazenda')], default='R', max_length=3, verbose_name='Street type'),
        ),
        migrations.AlterField(
            model_name='warehousetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='warehousetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
