# Generated by Django 5.1 on 2025-02-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coustcenter'),
        ('warehouse', '0007_alter_stock_options_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='coust_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coustcenter', verbose_name='Centro de Custo'),
        ),
    ]
