# Generated by Django 5.1 on 2024-10-07 18:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_enterprise_identification_number'),
        ('product', '0003_alter_product_options_alter_productcategory_options_and_more'),
        ('warehouse', '0003_alter_storagebin_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('street_type', models.CharField(choices=[('AV', 'Avenida'), ('R', 'Rua'), ('T', 'Travessa'), ('FAZ', 'Fazenda')], default='R', max_length=3)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=50, null=True)),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fantasy_name', models.CharField(max_length=50)),
                ('person_type', models.CharField(choices=[('PJ', 'Pessoa Física'), ('PF', 'Pessoa Jurídica')], max_length=50)),
                ('cpf_or_cnpj', models.CharField(max_length=14)),
                ('rg_or_ie', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('is_supplier', models.BooleanField()),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_address', to='purchase.address')),
                ('principal_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='principal_address', to='purchase.address')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('code', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Rascunho'), ('Approved', 'Aprovado'), ('Rejected', 'Rejeitado'), ('Delivery', 'Para Entrega'), ('Concluded', 'Concluído'), ('Late', 'Entrega Atrasada'), ('Canceled', 'Cancelado')], default='Draft', max_length=9)),
                ('delivery_forecast', models.DateField()),
                ('approval_date', models.DateField(null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.enterprise')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.person')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('purchase_order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='items',
            field=models.ManyToManyField(through='purchase.PurchaseOrderItems', to='product.product'),
        ),
    ]
