# Generated by Django 5.1 on 2025-02-14 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_alter_productcategory_options_and_more'),
        ('purchase', '0002_alter_person_options_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='QTD'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Un (R$)'),
        ),
    ]
