# Generated by Django 5.1 on 2024-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_number', models.IntegerField(verbose_name='Budget number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Order',
                'db_table': 'service_orders',
            },
        ),
    ]
