# Generated by Django 5.1 on 2024-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_vacation_unique_employee_hiring_start_and_end_date'),
        ('tool', '0002_alter_brand_options_alter_toolcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tooldistributionrecord',
            name='unique_tool_employee',
        ),
        migrations.AddConstraint(
            model_name='tooldistributionrecord',
            constraint=models.UniqueConstraint(fields=('tool', 'employee', 'issue_date'), name='unique_tool_employee_date'),
        ),
    ]
